### PR TITLE
Filter limit checkbox added

### PR DESCRIPTION
**Pull request by Evan-CTL**
Other adjustments made according to this Jira ticket: https://columbiactl.atlassian.net/browse/STAT-26?filter=10143

### CODE REVIEW

**Comment by ndittren** [comment]
Wouldn't the limit apply only to Popularity and not A-Z?

**Comment by ndittren** [comment]
I don't really have a preference, just going by what Mike said in the ticket

**Comment by Evan-CTL** [comment]
I'll ask him

**Comment by Evan-CTL** [comment]
Removed the checkbox from the alphabetical sorts

**Pull request merged**
