### PR TITLE
Y-axis on the line graph now adapts to datapoints

### PR DESCRIPTION
**Pull request by Evan-CTL**
This required a bit of a refactor for the line graph, but I tried to maintain as close to the original structure as I could. Running on a brand new Mac I didn't experience any slow down but that might not be the case for older devices, especially on moblie.
Closes #195

### CODE REVIEW

**Comment by ndittren** [comment]
In the inferential module the y-axis has a static range much like it is now. In the comparing genres modules, genre 1 plots somewhere way above the graph, screenshot below: 
Screen Shot 2023-10-24 at 11 20 29 AM

**Comment by ndittren** [comment]
The x-axis is not scaling like it should here.

**Comment by ndittren** [comment]
There is some weird stuff going on when in default 
Screen Shot 2023-10-31 at 10 24 09 AM

The range for the y-axis also just looks pretty similar to what it's doing now with just more ticks. 

I think we should table this for now.

**Comment by Evan-CTL** [comment]
This was actually intentional just to have a range that would be caught by the range function. I think I might have a better fix for it, but let me rebase first and see how that affects the code base.

**Comment by Evan-CTL** [comment]
Alright, now it will default to displaying the min and max defaults from the binData

**Comment by ndittren** [comment]
There are changes here for the estimated distribution graph. Can we keep that in a separate pr?

**Comment by ndittren** [comment]
When you draw one data point the first time, it's plotted all the way on the right side of the graph instead of in the middle, making it harder to see

**Comment by Evan-CTL** [comment]
> There are changes here for the estimated distribution graph. Can we keep that in a separate pr?

Yes, sorry. I can split it up. It was just one of those "Oh while I'm in here I'll make these tweaks" moments

**Comment by Evan-CTL** [comment]
> There are changes here for the estimated distribution graph. Can we keep that in a separate pr?

Resolved by #254

**Pull request merged**
