### PR TITLE
Data is stored between Comparing Genres and Confidence Intervals

### PR DESCRIPTION
**Pull request by Evan-CTL**

### CODE REVIEW

**Comment by ndittren** [comment]
Can you put a little more detail on what's happening in this PR? Seems like a lot of refactoring, I'm trying to piece it together.

**Comment by ndittren** [comment]
Also in comparing genres, when you click a genre1 and genre2 and hit Reset, it crashes the site.

**Comment by Evan-CTL** [comment]
Sorry. To elaborate:
The data is kept as a state in the app component and passed down along with the setState function via the GraphProps interface. It needs to be passed to each module. In the first two the data will be cleared, otherwise any changes to the parameters and the generated datasets will be shared between module 3 and 4. Because all of the modules use the same graphForm component it was easier for me to pass empty stores to the first two modules and exclude the setStore function, otherwise I would have had to define null states all over the graphForm and all of the graph components. In this way the graphForm checks to see if there is stored data before setting the defaults. I had to change a few things around from null to "default empty" values due to typescript nonsense.

`reset()` just restores the original state.

**Comment by ndittren** [comment]
Hey @Evan-CTL it looks like you combined all the already merged changes here. Can you try reverting that and just run a git rebase main? I think that should squash these commits.

**Pull request merged**
