### PR TITLE
Generate a legend for 2 genre graphs

### PR DESCRIPTION
**Pull request by Evan-CTL**
The layout is a compromise of the SVG positioning. D3 doesn't allow for percentage values relative to the width of an object, nor does it create a bounding box around sub-elements. What I could do was pin the dots in the upper right hand corner and anchor the text to it so variable string length didn't matter.

Includes some minor changes to `common.tsx`, keeping with the convention of ALL-CAPS for constants.

### CODE REVIEW

**Comment by ndittren** [comment]
Getting some weird background stuff here. And also noticed that sometimes the bar goes over the 20 ticker on the y-axis
Screen Shot 2023-07-25 at 9 56 49 AM

**Comment by ndittren** [comment]
Hm I would prefer to increase the y-axis after a threshold. But if they are really set on a fixed y-axis then yeah some visual indicator would be great.

**Comment by ndittren** [comment]
@Evan-CTL  is this ready to be reviewed again? We should hold off on changing the graph backgrounds until Marc takes a look at the colors and other design aspects of the page. Tag me in a comment when this is ready so I know to check.

**Comment by Evan-CTL** [comment]
@ndittren This is ready to review. I think the graph colors are easy enough to change if we want to but the professors expressed an interest in a graph background to contrast with the black margins, so I figured I'd include it.

**Pull request merged**
